#44) Pentagon numbers
#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

#%% Solution
from math import sqrt

def is_penta(x):
    return (sqrt(24*x+1)+1) % 6 == 0 if x > 0 else False

def penta_nums(x):
    n = 1
    while int(n*(3*n-1)/2) <= x:
        yield int(n*(3*n-1)/2)
        n += 1

list_pentagonal = list(penta_nums(10000000))

list_combinations = [
    (x,y)
    for x in list_pentagonal
    for y in list_pentagonal
    if is_penta(x+y)
    and is_penta(y-x)
]

list_combinations[0][1] - list_combinations[0][0]
